title = "ğŸ‘¨ğŸ»â€ğŸ’» Shiny Zhu"
baseURL = "https://shinyzhu.com/"
defaultContentLanguage = "en"
languageCode = "en-us"
copyright = "Shiny Zhu 2023"
theme = "diary"
googleAnalytics = "G-6BNX000R1H"

[params]
    subtitle = "âŒ¨ï¸ Full Stack + ğŸ¥‘ DevRel"
    enableAutoDarkMode = false
    enableUtterances = false
    enableGiscus = true
    enableReadingTime = true
    favicon = "/favicon.ico"
    # Microsoft Clarity
    clarity = "gjcjqcgtzd"

    # Twitter Card and Open Graph settings
    enableOpenGraph = true
    enableTwitterCards = true
    title = "Shiny Zhu" # will set 'og:site_name'
    description = "Blog on Full Stack and DevRel and much more." # will set 'og:description'
    images = ['/img/opengraph-card.png'] # will set 'og:image' and twitter card

[params.giscus]
    data_repo = "shinyzhu/shinyzhu.github.io"
    data_repo_id = "R_kgDOIwZXkQ"    
    data_category = "Comments"
    data_category_id = "DIC_kwDOIwZXkc4CTorA"
    data_mapping = "pathname"
    data_strict = "0"
    data_reactions_enabled = "1"
    data_emit_metadata = "0"
    data_input_position = "bottom"
    data_theme = "preferred_color_scheme"
    data_lang = "en"
    crossorigin = "anonymous"

[params.social]
    twitter = 'shinyzhu'

[[menu.main]]
    url = "/posts"
    name = "Posts ğŸ“‘"
    weight = 1
[[menu.main]]
    url = "/categories"
    name = "Categories ğŸ—‚ï¸"
    weight = 2
[[menu.main]]
    url = "/tags"
    name = "Tags ğŸ·ï¸"
    weight = 3
[[menu.main]]
    url = "/about"
    name = "About ğŸ‘¨ğŸ»â€ğŸ’»"
    weight = 4

[taxonomies]
   tag = "tags"
   category = "categories"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    noClasses = true
    style = "dracula"
    tabWidth = 4
